server:
  port: 8081

# 数据源
spring:
  datasource:
    driver-class-name : com.mysql.jdbc.Driver
    url : jdbc:mysql://120.78.170.112:3306/epublibsever?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=PRC&useSSL=false
    username : root
    password : Skx123@cug.com
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 500MB


file:
  uploadPath: C:\Users\skittle\IdeaProjects\epublib

